package claims

// Register is the claim surface. Discovered from README, CLI help, ADRs,
// docs/ and the code itself, not supplied by hand from marketing copy.
//
// Ordering is by subject, not by confidence. A DELIBERATE_NON_CLAIM sits
// beside an ESTABLISHED one on purpose: the decision not to assert something
// is part of the claim surface and is as load-bearing as an assertion.
var Register = []Claim{
	// ---------------------------------------------------------- measurement
	{
		ID:       "RPL-C001",
		Text:     "Replay reads agent transcripts already on disk and attributes prompt-cache behaviour per turn, without provider cooperation.",
		Asserted: []string{"README.md:13", "cmd/replay/main.go:639"},
		Scope:    "Claude Code, Codex, Grok, Ollama transcripts on local disk. Not Cursor, AnythingLLM or OpenClaw, which have no readable usage field.",
		Establishes: []string{
			"a per-turn record can be reconstructed from local artifacts alone",
		},
		DoesNotEstablish: []string{
			"that the reconstruction matches the provider's own accounting",
			"that any surface other than the four named ones can be read",
			"anything about surfaces whose usage field is absent or always zero",
		},
		Vocabulary: "surface.Class",
		Oracle:     "fixture corpora under internal/surface/testdata classified by an audit performed independently of the classifier",
		Tests:      []string{"TestFixtureCorporaClassifyAsTheAuditFound", "TestE2E_Diff", "TestE2E_Cost"},
		Result:     Bounded,
		Why:        "Holds for four surfaces and is explicitly refused for three others. The bound is the claim.",
	},
	{
		ID:          "RPL-C004",
		Text:        "Every figure Replay prints carries a truth tier: measured, estimated or structural.",
		Asserted:    []string{"README.md:293", "docs/adr/0002-replay-engine-and-truth-tiers.md:12"},
		Scope:       "printed output of the shipped binary, human and machine-readable",
		Establishes: nil,
		DoesNotEstablish: []string{
			"the universal form. `replay cost --json` emits dollar figures under seven top-level keys and not one of them names a tier, a provenance or a basis. A machine consumer receives money with no way to tell how it was obtained",
			"that the tier vocabulary is the mechanism anywhere. The human cost report labels its dollars by naming a dated price basis and uses none of the three tier words to do it",
			"ASSUMPTION, not established: that a tier is conveyed by those three words. A report conveying provenance by other wording is understated by this measurement, and the cost report turned out to be exactly that case",
		},
		Vocabulary: "",
		Oracle:     "the real cost report run over a fixture corpus and read as text, plus the parsed JSON document",
		Tests: []string{
			"TestC004_TheCostReportStatesHowItsDollarsWereObtained",
			"TestC004_TheTierVocabularyIsNotHowTheCostReportLabelsMoney",
			"TestC004_TheTierDetectorDiscriminates",
			"TestC004_TheJSONSurfaceCarriesNoTierField",
		},
		Result: Refuted,
		Why:    "Split into RPL-C027, RPL-C028 and RPL-C029, which carry three different proof obligations. Falsified as worded, by the machine-readable surface. Separately the three-word vocabulary is not how the human report labels money, and the two documents asserting the claim disagree on what the words are: README names three tiers, ADR-0002 is titled two and never contains the word structural. What is true is registered as RPL-C025 rather than read back into this one.",
	},
	{
		ID:       "RPL-C025",
		Text:     "The human cost report states the basis of its dollar figures, with a date, above the figures themselves.",
		Asserted: []string{"cmd/replay/cost.go:1057"},
		Scope:    "`replay cost` human output. NOT the JSON surface, and not established for any other report",
		Establishes: []string{
			"a reader meeting the money also meets the basis it was computed on and the date that basis was read",
			"the report says plainly that on a subscription seat the dollars are list price for someone billed per token",
		},
		DoesNotEstablish: []string{
			"anything about reports other than `replay cost`. The printed surface was not enumerated",
			"that the basis is correct, only that it is stated",
		},
		Vocabulary: "",
		Oracle:     "the rendered report inspected as text, with the header isolated from the figures",
		Tests:      []string{"TestC004_TheCostReportStatesHowItsDollarsWereObtained"},
		Result:     Bounded,
		Why:        "Mutation-proven at two points in cmd/replay/cost.go: removing the price basis from the header kills it, and removing the date kills it separately.",
	},
	{
		ID:       "RPL-C011",
		Text:     "The 'measured' truth tier means the provider reported the USAGE, not that the provider reported the CHARGE.",
		Asserted: []string{"README.md:299"},
		Scope:    "all dollar figures, including those obtained through replay serve",
		Establishes: []string{
			"token counts in the measured tier came from the provider's own counters",
		},
		DoesNotEstablish: []string{
			"that the dollar figure beside them is what the provider billed",
			"that the price table matched the account's negotiated rate",
			"that the figure is reconcilable with an invoice",
			"ASSUMPTION, not established: that the compiled price table matches the rate the account was actually billed on. Replay cannot check this, and the figure is wrong by exactly the discount where it does not hold",
		},
		Vocabulary: "",
		Oracle:     "independent reimplementation of the cost arithmetic in the test, not an import of CostLegsUSD",
		Tests: []string{
			"TestC011_IndependentArithmeticAgreesWithProduction",
			"TestC011_MeasuredUsageTimesLocalPriceIsNotABill",
			"TestC011_ThePriceBasisDeclaresItsOwnProvenanceAndAge",
			"TestC012_NoProviderBillingEndpointExists",
		},
		Result: Bounded,
		Why:    "Usage is provider-reported. Price is a local table. Their product is reconstructed, and the word 'measured' covers only the first factor.",
	},
	{
		ID:          "RPL-C012",
		Text:        "Replay can establish what a provider actually billed.",
		Asserted:    nil,
		Scope:       "all providers",
		Establishes: nil,
		DoesNotEstablish: []string{
			"anything. No code path reaches a provider invoice, balance or usage-report endpoint",
		},
		Vocabulary: "",
		Oracle:     "static scan of every outbound HTTP destination in non-test code",
		Tests:      []string{"TestC012_NoProviderBillingEndpointExists"},
		Result:     NoEndpoint,
		Why:        "Structural, not incidental. Every dollar figure in the repository is usage times a locally held price table. The only second source, LiteLLM, is documented in-code as an observer and not an authority.",
	},
	{
		ID:          "RPL-C024",
		Text:        "Attributed prompt tokens sum back to the provider's reported prompt total, with any excess carried in a named re-billed row rather than absorbed.",
		Asserted:    []string{"internal/analysis/conservation_test.go:12"},
		Scope:       "blame and reconcile output",
		Establishes: []string{"no token is silently dropped or double-counted in attribution"},
		DoesNotEstablish: []string{
			"that the split between buckets is correct. Conservation pins the total and says nothing about the division",
		},
		Vocabulary: "",
		Oracle:     "hand-computed totals in the conservation fixtures",
		Tests:      []string{"TestConserve_EveryBilledTokenLandsInExactlyOneBucket", "TestConserve_EachLaneConservesIndependently"},
		Result:     Bounded,
		Why:        "A necessary condition that the repository's own tests already state is not sufficient.",
	},

	// ------------------------------------------------------------- refusals
	{
		ID:       "RPL-C027",
		Text:     "A truth vocabulary exists: a defined, agreed set of tier words.",
		Asserted: []string{"README.md:293", "docs/adr/0002-replay-engine-and-truth-tiers.md:12"},
		Scope:    "the specification, not any output",
		Establishes: []string{
			"the words measured, estimated and structural appear in the product and in its documentation",
		},
		DoesNotEstablish: []string{
			"that the set is agreed. ADR-0002 is titled two tiers of truth and names estimated and measured; README names three, adding structural; and of 28 ADRs none supersedes 0002. The authoritative vocabulary is in conflict and nothing resolves it",
			"that the vocabulary is a type. There is no enum, no field and no enforcement: 15+ free string literals across 11 packages",
		},
		Vocabulary: "",
		Oracle:     "the two specification documents read directly, with a test that fails if either changes",
		Tests:      []string{"TestC004_TheTierSpecificationIsInConflict"},
		Result:     Unresolved,
		Why:        "The words exist and the specification disagrees with itself. A vocabulary two documents define differently is not yet a vocabulary, and this campaign declines to invent a third tier to reconcile them.",
	},
	{
		ID:          "RPL-C028",
		Text:        "Every relevant printed output carries a truth status.",
		Asserted:    []string{"README.md:293"},
		Scope:       "14 CLI surfaces sharing one callable signature, driven over a ledger fixture",
		Establishes: nil,
		DoesNotEstablish: []string{
			"the claim. `replay advise` is a CONFIRMED COUNTEREXAMPLE: it emits 10% without a status statement, isolated by removing it from the sweep, where figures fall 4 to 3 while status holds at 3. The campaign does NOT establish that it is the only such surface",
			"anything about 5 of the 14 surfaces. budget, ceiling, prefix and route did not run against this fixture and were not measured",
			"an exhaustive inventory of JSON figures. Two separate facts: DIRECT STRUCTURAL INSPECTION established that `replay cost --json` attaches no tier, provenance or basis field to its numerical values, and SEPARATELY the figure detector under-detected JSON because it looks for a dollar sign while JSON emits bare numbers such as totalUsd. The detector limitation is campaign evidence, not a product pass, and the inventory row for that surface must not be read as one",
			"ASSUMPTION, not established: that a status is conveyed by a tier word, a dated basis, a list-price statement or a refusal. The detector is deliberately generous, so a surface it marks as failing has really failed",
		},
		Vocabulary: "",
		Oracle:     "a text-level reference judgement over the fixture's own ground truth, which never calls Replay's classification code because none exists to call",
		Tests: []string{
			"TestC004_OutputSurfaceInventory",
			"TestC004_TheSurfaceDetectorsDiscriminate",
			"TestC004_TheJSONSurfaceCarriesNoTierField",
		},
		Result: Refuted,
		Why:    "Falsified by at least one surface, with 5 of 14 unmeasured and the JSON row under-measured by the detector's own admission. The partial coverage makes it weaker as a census and no weaker as a falsification: one counterexample is enough.",
	},
	{
		ID:          "RPL-C029",
		Text:        "The truth status a figure carries is epistemically correct.",
		Asserted:    nil,
		Scope:       "any figure carrying a status",
		Establishes: nil,
		DoesNotEstablish: []string{
			"anything. There is no machine-readable status attached to any figure, so there is nothing to compare against a ground truth. An absent status cannot be wrong, only missing",
		},
		Vocabulary: "",
		Oracle:     "none is constructible. The mutations this would need, altering a tier/value association or flipping observed to estimated, have no association to alter",
		Tests:      []string{"TestC004_OutputSurfaceInventory"},
		Result:     NoEndpoint,
		Why:        "NO_ENDPOINT rather than NOT_MEASURED, and the distinction is the finding. Nothing was left unmeasured: there is no status attached to any figure, so there is nothing that could be correct or incorrect. Correctness of a label is a separate obligation from presence of one, and presence fails first. This is NOT a recommendation to build a tier system.",
	},
	{
		ID:          "RPL-C005",
		Text:        "Anything Replay cannot measure it declines to print, and says why in the place the number would have gone.",
		Asserted:    []string{"README.md:21"},
		Scope:       "printed output of `replay cost`, human and JSON",
		Establishes: nil,
		DoesNotEstablish: []string{
			"the claim as worded. A transcript holding two priceable and two unpriceable requests produces a printed total over the priceable half only, with NO disclosure in the human report and `unpriced` reporting 0 in the JSON",
			"that the disclosure sentence is reachable per record. cost.go:488 exists and fires only when a WHOLE transcript is unpriced, because `unpriced` has transcript granularity while pricing has record granularity",
			"ASSUMPTION, not established: that a refusal is conveyed by the words unpriced, not priced or excluded. A refusal worded otherwise would be understated by this measurement",
		},
		Vocabulary: "surface.Class, surface.WriteContract, for the internal layer only",
		Oracle:     "the real cost report over a corpus whose unpriceability is verified independently with cachemodel.PriceFor before any output is read",
		Tests: []string{
			"TestC005_TheFixtureIsolatesExactlyOneUnmeasurableQuantity",
			"TestC005_AMixedTranscriptHidesItsUnpricedRecords",
			"TestC005_TheHumanReportAssertsCompletenessOverAPartlyPricedCorpus",
			"TestC005_AFullyPricedCorpusCorrectlyDisclosesNothing",
		},
		Result: Refuted,
		Why:    "Falsified at the printed surface, which is where the claim is made. The report prints a figure it could only partly compute and then states that it is what the work cost. The internal refusal machinery is correct and is registered separately as RPL-C026 rather than used to rescue this wording.",
	},
	{
		ID:       "RPL-C026",
		Text:     "Replay's surface classifier refuses to reach a verdict when the evidence cannot support one, and gives a reason.",
		Asserted: []string{"internal/surface/identify.go:174", "cmd/replay/doctor.go"},
		Scope:    "surface.Classify, and its verdict with reason on `replay doctor`'s cache signal line since 2026-10-02. NOT the cost report's printed figures, which RPL-C005 refutes",
		Establishes: []string{
			"an empty corpus, and zero write observations under an unknown provider contract, both reach ClassUndetermined",
			"the refusal carries a reason rather than arriving as a bare verdict",
			"an unsourced contract fact is rejected outright, so an assertion with no provenance cannot enter as a provider fact",
			"the verdict and its reason reach the user: replay doctor prints the class and, on an empty boundary, undetermined with the reason, through the shipped dispatch path",
		},
		DoesNotEstablish: []string{
			"that every refusal reaches the user. RPL-C005 establishes that the cost report's does not; this claim's reaches doctor",
			"that every refusal site is correct; reachability is machine-checked per site by scripts/refusal-reachability, correctness is not",
		},
		Vocabulary: "surface.Class, surface.WriteContract",
		Oracle:     "paired fixtures whose correct verdict is known from the contract, not from the classifier",
		Tests:      []string{"TestC005_RefusalIsDistinguishableFromZero", "TestC005_AnUnsourcedContractIsRefused", "TestE2E_Doctor", "TestE2E_DoctorRefusesToClassifyAnEmptyBoundary"},
		Result:     Bounded,
		Why:        "The classifier does what the claim describes and, since 2026-10-02, its verdict and reason are printed by replay doctor. The bound is the surface: doctor only, for the Anthropic transcript boundary, under a contract fact doctor states with its source. The cost report's own refusal (RPL-C005) is a separate finding.",
	},
	{
		ID:       "RPL-C034",
		Text:     "When a model has no price, Replay never reports its cost as zero.",
		Asserted: []string{"docs/TOKEN-PRICES.md:53"},
		Scope:    "MEASURED SURFACES ONLY, narrowed 2026-10-01 to what the evidence covers: the re-billed token count in `replay cost` and the worst-window ranking in `replay since`. The original scope said every consumer of cachemodel.PriceFor and PriceForAt, and 7 of 8 consumers were never measured at the user-visible boundary",
		DoesNotEstablish: []string{
			"anything about the other consumers of the price boolean. One was repaired; the remaining sites were censused from source and NEVER measured at the user-visible boundary, so TOKEN-PRICES.md:53 is NOT established as satisfied for them",
			"that 8 consumer sites are defective. That census was too coarse and is RETRACTED: most sites gate only dollars, which require a price, and order.go and trim.go carry presence flags the detector missed. The source census was necessary and not sufficient",
			"that the remaining sites are equivalent to each other. The 9 that handle it use at least four different conventions, so there is no shared contract in code, only a shared document",
			"the magnitude on any surface. The call-site census is established; what each silent zero does to a printed figure is measured only for cost.go and route.go",
		},
		Vocabulary: "",
		Oracle:     "a source census classifying each false branch, with the contract quoted from the repository's own document rather than assumed",
		Tests: []string{
			"TestEC00_ThePriceBooleanIsTheSharedCompressionPoint",
			"TestCW1_TheFourStates",
			"TestCW2_ColdAndWarmAgree",
			"TestCW3_RankingHoldsColdAndWarm",
			"TestRB2_AKnownDeficitIsReportedWhetherOrNotAPriceExists",
			"TestRB5_AnUnpricedSessionCannotBeNamedTheWorstWindow",
		},
		Establishes: []string{
			"9 of 19 call sites count the exclusion, refuse with a reason, or substitute a labelled upper bound",
			"at the two measured surfaces, a known re-billed token count survives an unavailable price. Two corpora differing only in a model id reported 40,000 tokens and 0 before 6794522 and report 40,000 on both arms after it",
			"`replay since` ranks by that count even when the price is unknown: with the unpriced session carrying four times the other's deficit, the command names it, cold and warm",
		},
		Result: Bounded,
		Why:    "CLOSED at the two surfaces that were measured and BOUNDED because the others were not. Repaired by 6794522 at three sites, verified cold and warm, and five mutations kill it. The original REFUTED verdict stands as the before state. CENSUS CORRECTED: a per-site audit found that most flagged sites compute their TOKEN quantities outside the price branch and gate only dollars, which is correct, and that order.go and trim.go carry presence flags the first detector missed. ONE price-independent quantity is suppressed, the re-billed token count, and a mutation campaign then corrected its attribution too: it is gated TWICE, at cost.go:680 and again at cost.go:717, and removing either alone changes nothing. Measured at the user-visible boundary as 40,000 tokens against 0 on corpora differing only in a model name.",
	},
	{
		ID:       "RPL-C033",
		Text:     "A dollar figure states the TTL basis its cache writes were priced on.",
		Asserted: []string{"README.md:293"},
		Scope:    "every surface printing a cache-write cost: burn, cost --usage, route",
		Establishes: []string{
			"where the provider supplies a TTL split, the distinction survives and prices correctly",
		},
		DoesNotEstablish: []string{
			"the claim where the provider supplies NO split. (*WireUsage).Usage() drops the presence bit the wire type carries, so an absent breakdown and a reported 0/0 arrive identically, and writeEquivalent then prices the whole write leg at the SHORT multiplier",
			"ASSUMPTION, not established: that an absent breakdown means a 5-minute TTL. It is the documented provider default and Replay never verifies it. The same 10,000 cache-creation tokens price at $0.037500 on that assumption and $0.060000 if the writes were in fact 1h, a 60% difference",
			"that the assumption is disclosed. It is declared in two code comments and in no output",
		},
		Vocabulary: "",
		Oracle:     "longhand multiplier arithmetic, independent of writeEquivalent",
		Tests: []string{
			"TestEC1_AbsentAndZeroTTLBreakdownAreIndistinguishable",
			"TestEC2_AnAbsentBreakdownIsPricedOnAnAssumedTTL",
			"TestEC3_TheAssumedDefaultIsDocumentedAtTheSite",
			"TestEC4_TheTTLDistinctionSurvivesWhereTheProviderSuppliesIt",
		},
		Result: Bounded,
		Why:    "Bounded rather than refuted, and the distinction matters. The collapse is declared at both sites, so this is not a silent defect; the TTL distinction is honoured wherever the provider reports it. What is undisclosed is that a figure computed on an absent breakdown rests on an assumed default, and the reader is given the dollars without the assumption.",
	},
	{
		ID:       "RPL-C030",
		Text:     "When a whole session cannot be priced, Replay refuses and says why.",
		Asserted: []string{"README.md:21", "cmd/replay/cost.go:488"},
		Scope:    "session granularity only",
		Establishes: []string{
			"a wholly unpriceable session is counted and disclosed",
			"a fully priceable corpus discloses nothing, so the refusal does not fire on everything",
			"a measurable session beside an unmeasurable one does NOT rescue it; foreign evidence is not borrowed",
		},
		DoesNotEstablish: []string{
			"anything below session granularity. RPL-C031 refutes that",
			"that the explanation is complete, only that it fires and is accurate when it does",
		},
		Vocabulary: "",
		Oracle:     "a fixture matrix whose ground truth the test constructs and therefore knows without reading it back",
		Tests:      []string{"TestC005M_FixtureAssumptionsHold", "TestC005M_TheFixtureMatrix"},
		Result:     Bounded,
		Why:        "MX1, MX2, MX4 and MX9 all behave correctly at session granularity. Three mutations on the refusal path all kill.",
	},
	{
		ID:          "RPL-C031",
		Text:        "Replay discloses partial coverage: when some records in a session cannot be priced, it says so.",
		Asserted:    []string{"README.md:21"},
		Scope:       "record granularity within one session",
		Establishes: nil,
		DoesNotEstablish: []string{
			"the claim. The counter operates at SESSION granularity and this claim is about RECORD granularity. A session holding two priceable and two unpriceable records has a priceable model on its first request, so it is not flagged, its unpriceable records still contribute nothing to the total, and nothing is disclosed on either surface",
			"UNCHANGED BY THE REPAIR OF 6794522, verified rather than assumed. That repair replaced an inferred priceability test with a real one at session granularity, which closed RPL-C032 and RPL-C034's measured surface. Re-measured afterwards, MX3 and MX10 still report unpriced=0 with no disclosure. A record-level counter is a separate change and was not made",
		},
		Vocabulary: "",
		Oracle:     "the record-level ground truth the fixture declares, compared against the printed figures",
		Tests:      []string{"TestC005M_TheFixtureMatrix", "TestC005_AMixedTranscriptHidesItsUnpricedRecords"},
		Result:     Refuted,
		Why:        "Reproduced from scratch with an independent oracle. The report prints a total over the measurable half and states that it is what the work cost. Re-evaluated after 6794522 and STILL REFUTED: that repair works at session granularity and this claim is about record granularity, so the two do not meet. Status unchanged on measurement, not on inference.",
	},
	{
		ID:       "RPL-C032",
		Text:     "Replay distinguishes a measured zero from an unmeasurable quantity.",
		Asserted: []string{"README.md:603"},
		Scope:    "session cost in `replay cost`",
		Establishes: []string{
			"a session that genuinely cost nothing is no longer reported as unpriced. The repair of 6794522 replaced `asRun.CostUSD <= 0` with a real price-table lookup, so priceability is asked rather than inferred from a cost of zero",
		},
		DoesNotEstablish: []string{
			"the distinction anywhere other than session cost in `replay cost`. The repair asked the price table directly at ONE site; no other site was revalidated",
			"anything about the three-state distinction elsewhere. RPL-C008 establishes it for cache counters, where WriteFieldPresent exists; this is a different site with no equivalent",
		},
		Vocabulary: "",
		Oracle:     "a session constructed with every usage field zero on a model verified priced before the run",
		Tests: []string{
			"TestC005M_TheFixtureMatrix",
			"TestCW1_TheFourStates",
			"TestRB6_AGenuineZeroIsNotTheSameAsUnavailable",
		},
		Result: Bounded,
		Why:    "CLOSED by 6794522 at the site it was raised against, and bounded because only that site was revalidated. Before: MX8 built a session with every usage field zero on a PRICED model and it reported unpriced=1. After: it reports 0, CW1's genuine-zero state passes, and the mutation that restores the inferred test is killed. The original REFUTED verdict stands as history; the first version of MX8 did not test this at all because it left cache usage priced, and that defect in the test is preserved in the evidence file.",
	},
	{
		ID:   "RPL-C037",
		Text: "The re-billed dollar figure and the re-billed token count `replay cost` prints together describe the same re-billing.",
		// Asserted by the rendering, not by prose: the two are printed as one
		// result, the second line indented under the first.
		Asserted: []string{"cmd/replay/cost.go:547", "cmd/replay/cost.go:549"},
		Scope:    "break granularity within `replay cost`, human and JSON surfaces",
		Establishes: []string{
			"the token count. RebilledTokens covers every break and is correct, which RPL-C036 settled",
			"the pairing is now disclosed rather than true. `replay cost` states what share of the re-billed tokens the dollar figure represents, floored and never clamped, and states the excluded count. Suppressed where nothing is excluded and where there was no break",
			"the disclosure describes the figure rather than the price lookup. A unit-flagged session's break tokens are excluded although every one of its breaks priced, which a per-break-only counter reported as 100% against a figure covering 33%",
		},
		DoesNotEstablish: []string{
			"the pairing itself, which is unchanged. RebilledUSD still covers only breaks whose own record could be priced, at cost.go:885 and again at cost.go:453, and RebilledTokens still counts every break at cost.go:433. The repair is a disclosure: no dollar and no token figure moved, which TestC037_P1 asserts in both directions",
			"anything about break COUNT coverage, which is deliberately not disclosed. On a corpus of one 90,000-token priceable break against three 1,000-token unpriceable ones, token coverage is 96% and count coverage 25%; the dollar figure is token-weighted, so the count would describe a different population",
			"any surface other than `replay cost`. `replay advise`, the card and the share surface read re-billed figures and were not examined for the same collapse",
			"that C035's disclosure covers this. That sentence is about requests and about TotalUSD; held identical across two corpora it leaves break coverage at 100% and 50% indistinguishable",
			"ASSUMPTION, not established: that a future disclosure would be recognisable to the frozen detector. It is proven against a planted sentence, not against a shipped one, and a disclosure worded without the words priced, price table or unpriceable would not be seen",
			"anything about `replay since`, which ranks on RebilledTokens alone and is outside this claim",
			"`replay cost --usage`, which is a SECOND path inside the same command with the same shape: costusage.go:194 accumulates sDeficit unconditionally, costusage.go:196 adds to sRebilled only `if priced`, and costusage.go:267 renders the two as one pair. Found by the post-repair surface audit, NOT measured and NOT repaired",
		},
		Vocabulary: "",
		Oracle:     "a break-token ledger computed from the fixture specification, never from RebilledUSD or RebilledTokens, compared against the rendered and serialized re-billing surface",
		Tests: []string{
			"TestC037_FixtureAssumptions",
			"TestC037_P1_TheRebillingSurfaceCollapses",
			"TestC037_P1b_RequestCoverageCarriesNoBreakCoverage",
			"TestC037_P2_NoBreakCoverageIsDisclosed",
			"TestC037_P3_FullCoverageEmitsNoPartialDisclosure",
			"TestC037_P4_ZeroBreakCorpusEmitsNoDisclosure",
			"TestC037_TheDetectorDiscriminates",
			"TestC037_TheOracleRejectsEveryWrongCandidate",
			"TestC037R1_TheFourCoverageCases",
			"TestC037R2_UnequalDeficitsRuleOutCountCoverage",
			"TestC037R3_TheUnitGateDecidesRepresentation",
			"TestC037R4_AZeroRatePriceableBreakIsFullyRepresented",
			"TestC037R5_ColdAndWarmDiscloseTheSame",
			"TestC037R6_TheIndexKeyCarriesTheCounter",
			"TestC037R7_TheCounterSurvivesTheLaneFold",
		},
		Result: Bounded,
		Why:    "REPAIRED 2026-10-02 by one counter, UnpricedRebilledTokens, and one disclosure. Frozen first: two corpora on one model name, 40,000 break tokens each, one fully priceable and one with 20,000 unpriceable, rendered an identical re-billed result and identical JSON. After the repair the 100% arm discloses nothing and the 50% arm discloses 50%, while both still report $0.020000 over 40,000 tokens. Ten production mutations killed, including count-based, request-based, per-break-only, forced-100%, inverted, and deriving priceability from a nonzero contribution; the lane-fold mutation SURVIVED first because every fixture was single-lane, and a two-lane case was added rather than the survivor explained away. Bounded because only `replay cost` was measured. cost.go:70-77's principle, that unpriced is not zero cost, now holds for RebilledUSD as it already did for CostUSD.",
	},
	{
		ID:               "RPL-C008",
		Text:             "Absence, zero and unknown are three different values, and Replay never collapses them.",
		Asserted:         []string{"README.md:603", "docs/adr/0018-provenance-is-a-field.md"},
		Scope:            "cache counters on every surface",
		Establishes:      []string{"a missing counter is reported as missing, not as zero"},
		DoesNotEstablish: []string{"that a reported zero is a true zero. That depends on the provider's contract, which may be unknown"},
		Vocabulary:       "surface.WriteContract, surface.Observables.WriteFieldPresent",
		Oracle:           "fixtures that omit a field versus fixtures that set it to zero, compared on output",
		Tests:            []string{"TestC008_AbsentFieldAndZeroFieldDiffer", "TestB5_AnOmittedQuantitativeKeyIsRefusedNotReadAsZero", "TestE2E_Cost"},
		Result:           Established,
		Why:              "Positive, negative and mutation controls all discriminate. WriteFieldPresent and PrefixMeasured exist for exactly this.",
	},

	// ------------------------------------------------- correlation and joins
	{
		ID:          "RPL-C019",
		Text:        "Replay distinguishes evidence belonging to different provider accounts.",
		Asserted:    nil,
		Scope:       "every correlation path: ledger, transcript readers, cost report",
		Establishes: nil,
		DoesNotEstablish: []string{
			"anything. No account, tenant, organisation, project or workspace identity exists anywhere in the correlation path. A ledger record carries SessionID, AgentID, RequestID and SessionHash and nothing that names whose account it was",
		},
		Vocabulary: "",
		Oracle:     "static scan of every non-test Go file for an account-shaped identity",
		Tests:      []string{"TestXW6_NoAccountIdentityExistsToCorrelateOn"},
		Result:     NoEndpoint,
		Why:        "Not a testing gap: there is no endpoint to test. Two records from different accounts sharing a provider request id are indistinguishable from the same request seen twice, because nothing in the evidence model names the account. Consistent with the distinct-account claim removed at 8e871bf as structurally unavailable, which needed a provider to issue an account-scoped credential and none does.",
	},
	{
		ID:       "RPL-C020",
		Text:     "Records from two different sessions are never combined into one history.",
		Asserted: []string{"cmd/replay/overlap.go:23", "cmd/replay/requestjoin_test.go:16"},
		Scope:    "cross-file and cross-session joins, ledger reader and cost report",
		Establishes: []string{
			"a locally synthesised id is never used as a join key, whatever it is spelled",
			"two sessions with no shared provider id are never reported as sharing a request, end to end through the cost report",
			"adding a foreign session's evidence does not change what is reported about the first",
		},
		DoesNotEstablish: []string{
			"that an id collision across sessions would be caught. Two requests on different models with different token counts merge on a shared provider id alone, because the join compares no other field. The implementation conforms to the current join contract under the provider-id uniqueness assumption; this campaign does NOT establish that Replay independently verifies that assumption. Observed under fixture, not theoretical: TestXW2 constructs it and the merge happens",
			"that evidence from two different provider accounts is distinguishable at all. There is no account identity in the model; see RPL-C019, which classifies that as NO_ENDPOINT rather than as an untested case",
		},
		Vocabulary: "transcript.Request.IDMeasured, transcript.Request.Correlation",
		Oracle:     "oracleJoin in cmd/replay/crosswire_test.go, a reference implementation of the stated rule that never calls requestJoin",
		Tests: []string{
			"TestXW1_LegitimateSessionsJoinWithinThemselvesAndNotAcrossThem",
			"TestXW2_AnIDCollisionAcrossSessionsMergesWithoutCorroboration",
			"TestXW3_ASuperficiallyCompatibleIdentifierDoesNotJoin",
			"TestXW4_TwoSessionsOnDiskDoNotShareUsage",
			"TestXW5_AddingAForeignSessionDoesNotChangeTheFirstSessionsFigures",
			"TestXW7_TheJoinContractBoundary",
			"TestRJ1_SynthesisedIDsAreNotJoinedAcrossFiles",
			"TestRJ2_ProviderIDsStillJoin",
		},
		Result: Bounded,
		Why:    "No tested cross-session fixture produced an unintended merge except the deliberate provider-id collision case. That case is an OBSERVED behaviour under a constructed fixture, not a theoretical limitation, and it demonstrates that current join safety depends on provider request-id uniqueness, which Replay does not independently establish.",
	},
	{
		ID:               "RPL-C021",
		Text:             "Replay offers no cross-surface grand total.",
		Asserted:         []string{"cmd/replay/burn.go:20"},
		Scope:            "replay burn",
		Establishes:      []string{"figures with incommensurable units are not added"},
		DoesNotEstablish: []string{"that per-surface figures are themselves comparable"},
		Vocabulary:       "",
		Oracle:           "type-level: the summary type exposes no addition; and behavioural: the rendered burn report, with two surfaces populated, carries no total line and not the sum of the per-surface figures",
		Tests:            []string{"TestC021_NoCrossSurfaceTotalIsReachable", "TestC021_BurnPrintsNoCrossSurfaceTotal"},
		Result:           Established,
		Why:              "Enforced by the shape of the type rather than by a convention, and a mutation that adds a total is caught.",
	},

	// ------------------------------------------- the deliberate non-claims
	{
		ID:               "RPL-C013",
		Text:             "Replay establishes realized savings.",
		Asserted:         nil,
		Scope:            "all output",
		Establishes:      nil,
		DoesNotEstablish: []string{"anything. The product explicitly refuses to forecast or claim savings"},
		Vocabulary:       "",
		Oracle:           "scan of user-facing strings for savings and forecast vocabulary",
		Tests:            []string{"TestC013_NoSavingsClaimReachesTheUser"},
		Result:           DeliberateNonClaim,
		Why:              "README:523 and the agent skill both forbid it. Payback computes a projection from two reconstructed costs under an unverifiable counterfactual, and labels it an assumption.",
	},
	{
		ID:          "RPL-C015",
		Text:        "Replay can establish that acting on its advice changed anything.",
		Asserted:    nil,
		Scope:       "advisor findings",
		Establishes: nil,
		DoesNotEstablish: []string{
			"outcome for KindCacheBreaks or KindHotFile, the two kinds carrying the largest predicted value",
		},
		Vocabulary: "advisor.Status",
		Oracle:     "the refusal is in the product: track returns AdviceOnly before any scoring runs",
		Tests:      []string{"TestC015_TheTwoLargestKindsAreRefusedScoring", "TestC015_VerifierInferenceIsNotAReaderDecision"},
		Result:     NotMeasured,
		Why:        "The verifier refuses by design, because a share that moves with the work cannot be attributed to a user action. The seeded-intervention pilot then failed its gating question.",
	},
	{
		ID:               "RPL-C016",
		Text:             "Replay improves agent task outcomes.",
		Asserted:         nil,
		Scope:            "durable work state",
		Establishes:      nil,
		DoesNotEstablish: []string{"anything in either direction"},
		Vocabulary:       "",
		Oracle:           "R10 hidden-oracle benchmark",
		Tests:            []string{"TestC016_NoTaskImprovementClaimIsAsserted"},
		Result:           NotMeasured,
		Why:              "R1 established retrieval, not outcome. The R10 trial on 2026-09-30 stopped at a preregistered ceiling and the treatment arm never ran.",
	},

	// -------------------------------------------------------- the footprint
	{
		ID:          "RPL-C022",
		Text:        "The binary makes no network request except for commands the user explicitly types.",
		Asserted:    []string{"README.md:407", "plugins/replay/skills/replay-doctor/SKILL.md:9"},
		Scope:       "the shipped binary",
		Establishes: []string{"no telemetry, no beacon, no first-run call"},
		DoesNotEstablish: []string{
			"anything about the hosted installer, which is checked separately",
			"ASSUMPTION, not established: that a destination is reachable only through a URL literal in Go source. A host assembled at runtime from parts would not be seen by this scan",
		},
		Vocabulary: "",
		Oracle:     "static enumeration of outbound destinations in non-test code",
		Tests:      []string{"TestC022_OutboundDestinationsAreAnEnumeratedSet"},
		Result:     Bounded,
		Why:        "Checkable statically. A dynamic proof would need a sandboxed run and is not attempted here.",
	},
}
