package claims

// Register is the claim surface. Discovered from README, CLI help, ADRs,
// docs/ and the code itself, not supplied by hand from marketing copy.
//
// Ordering is by subject, not by confidence. A DELIBERATE_NON_CLAIM sits
// beside an ESTABLISHED one on purpose: the decision not to assert something
// is part of the claim surface and is as load-bearing as an assertion.
var Register = []Claim{
	// ---------------------------------------------------------- measurement
	{
		ID:       "RPL-C001",
		Text:     "Replay reads agent transcripts already on disk and attributes prompt-cache behaviour per turn, without provider cooperation.",
		Asserted: []string{"README.md:13", "cmd/replay/main.go:639"},
		Scope:    "Claude Code, Codex, Grok, Ollama transcripts on local disk. Not Cursor, AnythingLLM or OpenClaw, which have no readable usage field.",
		Establishes: []string{
			"a per-turn record can be reconstructed from local artifacts alone",
		},
		DoesNotEstablish: []string{
			"that the reconstruction matches the provider's own accounting",
			"that any surface other than the four named ones can be read",
			"anything about surfaces whose usage field is absent or always zero",
		},
		Vocabulary: "surface.Class",
		Oracle:     "fixture corpora under internal/surface/testdata classified by an audit performed independently of the classifier",
		Tests:      []string{"TestFixtureCorporaClassifyAsTheAuditFound"},
		Result:     Bounded,
		Why:        "Holds for four surfaces and is explicitly refused for three others. The bound is the claim.",
	},
	{
		ID:          "RPL-C004",
		Text:        "Every figure Replay prints carries a truth tier: measured, estimated or structural.",
		Asserted:    []string{"README.md:293", "docs/adr/0002-replay-engine-and-truth-tiers.md:12"},
		Scope:       "printed output of the shipped binary, human and machine-readable",
		Establishes: nil,
		DoesNotEstablish: []string{
			"the universal form. `replay cost --json` emits dollar figures under seven top-level keys and not one of them names a tier, a provenance or a basis. A machine consumer receives money with no way to tell how it was obtained",
			"that the tier vocabulary is the mechanism anywhere. The human cost report labels its dollars by naming a dated price basis and uses none of the three tier words to do it",
			"ASSUMPTION, not established: that a tier is conveyed by those three words. A report conveying provenance by other wording is understated by this measurement, and the cost report turned out to be exactly that case",
		},
		Vocabulary: "",
		Oracle:     "the real cost report run over a fixture corpus and read as text, plus the parsed JSON document",
		Tests: []string{
			"TestC004_TheCostReportStatesHowItsDollarsWereObtained",
			"TestC004_TheTierVocabularyIsNotHowTheCostReportLabelsMoney",
			"TestC004_TheTierDetectorDiscriminates",
			"TestC004_TheJSONSurfaceCarriesNoTierField",
		},
		Result: Refuted,
		Why:    "Falsified as worded, by the machine-readable surface. Separately the three-word vocabulary is not how the human report labels money, and the two documents asserting the claim disagree on what the words are: README names three tiers, ADR-0002 is titled two and never contains the word structural. What is true is registered as RPL-C025 rather than read back into this one.",
	},
	{
		ID:       "RPL-C025",
		Text:     "The human cost report states the basis of its dollar figures, with a date, above the figures themselves.",
		Asserted: []string{"cmd/replay/cost.go:1057"},
		Scope:    "`replay cost` human output. NOT the JSON surface, and not established for any other report",
		Establishes: []string{
			"a reader meeting the money also meets the basis it was computed on and the date that basis was read",
			"the report says plainly that on a subscription seat the dollars are list price for someone billed per token",
		},
		DoesNotEstablish: []string{
			"anything about reports other than `replay cost`. The printed surface was not enumerated",
			"that the basis is correct, only that it is stated",
		},
		Vocabulary: "",
		Oracle:     "the rendered report inspected as text, with the header isolated from the figures",
		Tests:      []string{"TestC004_TheCostReportStatesHowItsDollarsWereObtained"},
		Result:     Bounded,
		Why:        "Mutation-proven at two points in cmd/replay/cost.go: removing the price basis from the header kills it, and removing the date kills it separately.",
	},
	{
		ID:       "RPL-C011",
		Text:     "The 'measured' truth tier means the provider reported the USAGE, not that the provider reported the CHARGE.",
		Asserted: []string{"README.md:299"},
		Scope:    "all dollar figures, including those obtained through replay serve",
		Establishes: []string{
			"token counts in the measured tier came from the provider's own counters",
		},
		DoesNotEstablish: []string{
			"that the dollar figure beside them is what the provider billed",
			"that the price table matched the account's negotiated rate",
			"that the figure is reconcilable with an invoice",
			"ASSUMPTION, not established: that the compiled price table matches the rate the account was actually billed on. Replay cannot check this, and the figure is wrong by exactly the discount where it does not hold",
		},
		Vocabulary: "",
		Oracle:     "independent reimplementation of the cost arithmetic in the test, not an import of CostLegsUSD",
		Tests: []string{
			"TestC011_IndependentArithmeticAgreesWithProduction",
			"TestC011_MeasuredUsageTimesLocalPriceIsNotABill",
			"TestC011_ThePriceBasisDeclaresItsOwnProvenanceAndAge",
			"TestC012_NoProviderBillingEndpointExists",
		},
		Result: Bounded,
		Why:    "Usage is provider-reported. Price is a local table. Their product is reconstructed, and the word 'measured' covers only the first factor.",
	},
	{
		ID:          "RPL-C012",
		Text:        "Replay can establish what a provider actually billed.",
		Asserted:    nil,
		Scope:       "all providers",
		Establishes: nil,
		DoesNotEstablish: []string{
			"anything. No code path reaches a provider invoice, balance or usage-report endpoint",
		},
		Vocabulary: "",
		Oracle:     "static scan of every outbound HTTP destination in non-test code",
		Tests:      []string{"TestC012_NoProviderBillingEndpointExists"},
		Result:     NoEndpoint,
		Why:        "Structural, not incidental. Every dollar figure in the repository is usage times a locally held price table. The only second source, LiteLLM, is documented in-code as an observer and not an authority.",
	},
	{
		ID:          "RPL-C024",
		Text:        "Attributed prompt tokens sum back to the provider's reported prompt total, with any excess carried in a named re-billed row rather than absorbed.",
		Asserted:    []string{"internal/analysis/conservation_test.go:12"},
		Scope:       "blame and reconcile output",
		Establishes: []string{"no token is silently dropped or double-counted in attribution"},
		DoesNotEstablish: []string{
			"that the split between buckets is correct. Conservation pins the total and says nothing about the division",
		},
		Vocabulary: "",
		Oracle:     "hand-computed totals in the conservation fixtures",
		Tests:      []string{"TestConserve_EveryBilledTokenLandsInExactlyOneBucket", "TestConserve_EachLaneConservesIndependently"},
		Result:     Bounded,
		Why:        "A necessary condition that the repository's own tests already state is not sufficient.",
	},

	// ------------------------------------------------------------- refusals
	{
		ID:               "RPL-C005",
		Text:             "Anything Replay cannot measure it declines to print, and says why in the place the number would have gone.",
		Asserted:         []string{"README.md:21"},
		Scope:            "all printed figures",
		Establishes:      []string{"absence of a figure is distinguishable from a figure of zero"},
		DoesNotEstablish: []string{"that every refusal is correct, only that refusals are reachable and distinguishable"},
		Vocabulary:       "surface.Class, surface.WriteContract",
		Oracle:           "scripts/refusal-reachability neutralises each refusal and requires the suite to notice",
		Tests:            []string{"TestC005_RefusalIsDistinguishableFromZero"},
		Result:           Bounded,
		Why:              "Reachability of refusals is machine-checked. Correctness of each refusal is per-site and is not established globally.",
	},
	{
		ID:               "RPL-C008",
		Text:             "Absence, zero and unknown are three different values, and Replay never collapses them.",
		Asserted:         []string{"README.md:603", "docs/adr/0018-provenance-is-a-field.md"},
		Scope:            "cache counters on every surface",
		Establishes:      []string{"a missing counter is reported as missing, not as zero"},
		DoesNotEstablish: []string{"that a reported zero is a true zero. That depends on the provider's contract, which may be unknown"},
		Vocabulary:       "surface.WriteContract, surface.Observables.WriteFieldPresent",
		Oracle:           "fixtures that omit a field versus fixtures that set it to zero, compared on output",
		Tests:            []string{"TestC008_AbsentFieldAndZeroFieldDiffer"},
		Result:           Established,
		Why:              "Positive, negative and mutation controls all discriminate. WriteFieldPresent and PrefixMeasured exist for exactly this.",
	},

	// ------------------------------------------------- correlation and joins
	{
		ID:          "RPL-C019",
		Text:        "Replay distinguishes evidence belonging to different provider accounts.",
		Asserted:    nil,
		Scope:       "every correlation path: ledger, transcript readers, cost report",
		Establishes: nil,
		DoesNotEstablish: []string{
			"anything. No account, tenant, organisation, project or workspace identity exists anywhere in the correlation path. A ledger record carries SessionID, AgentID, RequestID and SessionHash and nothing that names whose account it was",
		},
		Vocabulary: "",
		Oracle:     "static scan of every non-test Go file for an account-shaped identity",
		Tests:      []string{"TestXW6_NoAccountIdentityExistsToCorrelateOn"},
		Result:     NoEndpoint,
		Why:        "Not a testing gap: there is no endpoint to test. Two records from different accounts sharing a provider request id are indistinguishable from the same request seen twice, because nothing in the evidence model names the account. Consistent with the distinct-account claim removed at 8e871bf as structurally unavailable, which needed a provider to issue an account-scoped credential and none does.",
	},
	{
		ID:       "RPL-C020",
		Text:     "Records from two different sessions are never combined into one history.",
		Asserted: []string{"cmd/replay/overlap.go:23", "cmd/replay/requestjoin_test.go:16"},
		Scope:    "cross-file and cross-session joins, ledger reader and cost report",
		Establishes: []string{
			"a locally synthesised id is never used as a join key, whatever it is spelled",
			"two sessions with no shared provider id are never reported as sharing a request, end to end through the cost report",
			"adding a foreign session's evidence does not change what is reported about the first",
		},
		DoesNotEstablish: []string{
			"that an id collision across sessions would be caught. Two requests on different models with different token counts merge on a shared provider id alone, because the join compares no other field. The implementation conforms to the current join contract under the provider-id uniqueness assumption; this campaign does NOT establish that Replay independently verifies that assumption. Observed under fixture, not theoretical: TestXW2 constructs it and the merge happens",
			"that evidence from two different provider accounts is distinguishable at all. There is no account identity in the model; see RPL-C019, which classifies that as NO_ENDPOINT rather than as an untested case",
		},
		Vocabulary: "transcript.Request.IDMeasured, transcript.Request.Correlation",
		Oracle:     "oracleJoin in cmd/replay/crosswire_test.go, a reference implementation of the stated rule that never calls requestJoin",
		Tests: []string{
			"TestXW1_LegitimateSessionsJoinWithinThemselvesAndNotAcrossThem",
			"TestXW2_AnIDCollisionAcrossSessionsMergesWithoutCorroboration",
			"TestXW3_ASuperficiallyCompatibleIdentifierDoesNotJoin",
			"TestXW4_TwoSessionsOnDiskDoNotShareUsage",
			"TestXW5_AddingAForeignSessionDoesNotChangeTheFirstSessionsFigures",
			"TestXW7_TheJoinContractBoundary",
			"TestRJ1_SynthesisedIDsAreNotJoinedAcrossFiles",
			"TestRJ2_ProviderIDsStillJoin",
		},
		Result: Bounded,
		Why:    "No tested cross-session fixture produced an unintended merge except the deliberate provider-id collision case. That case is an OBSERVED behaviour under a constructed fixture, not a theoretical limitation, and it demonstrates that current join safety depends on provider request-id uniqueness, which Replay does not independently establish.",
	},
	{
		ID:               "RPL-C021",
		Text:             "Replay offers no cross-surface grand total.",
		Asserted:         []string{"cmd/replay/burn.go:20"},
		Scope:            "replay burn",
		Establishes:      []string{"figures with incommensurable units are not added"},
		DoesNotEstablish: []string{"that per-surface figures are themselves comparable"},
		Vocabulary:       "",
		Oracle:           "type-level: the summary type exposes no addition",
		Tests:            []string{"TestC021_NoCrossSurfaceTotalIsReachable"},
		Result:           Established,
		Why:              "Enforced by the shape of the type rather than by a convention, and a mutation that adds a total is caught.",
	},

	// ------------------------------------------- the deliberate non-claims
	{
		ID:               "RPL-C013",
		Text:             "Replay establishes realized savings.",
		Asserted:         nil,
		Scope:            "all output",
		Establishes:      nil,
		DoesNotEstablish: []string{"anything. The product explicitly refuses to forecast or claim savings"},
		Vocabulary:       "",
		Oracle:           "scan of user-facing strings for savings and forecast vocabulary",
		Tests:            []string{"TestC013_NoSavingsClaimReachesTheUser"},
		Result:           DeliberateNonClaim,
		Why:              "README:523 and the agent skill both forbid it. Payback computes a projection from two reconstructed costs under an unverifiable counterfactual, and labels it an assumption.",
	},
	{
		ID:          "RPL-C015",
		Text:        "Replay can establish that acting on its advice changed anything.",
		Asserted:    nil,
		Scope:       "advisor findings",
		Establishes: nil,
		DoesNotEstablish: []string{
			"outcome for KindCacheBreaks or KindHotFile, the two kinds carrying the largest predicted value",
		},
		Vocabulary: "advisor.Status",
		Oracle:     "the refusal is in the product: track returns AdviceOnly before any scoring runs",
		Tests:      []string{"TestC015_TheTwoLargestKindsAreRefusedScoring", "TestC015_VerifierInferenceIsNotAReaderDecision"},
		Result:     NotMeasured,
		Why:        "The verifier refuses by design, because a share that moves with the work cannot be attributed to a user action. The seeded-intervention pilot then failed its gating question.",
	},
	{
		ID:               "RPL-C016",
		Text:             "Replay improves agent task outcomes.",
		Asserted:         nil,
		Scope:            "durable work state",
		Establishes:      nil,
		DoesNotEstablish: []string{"anything in either direction"},
		Vocabulary:       "",
		Oracle:           "R10 hidden-oracle benchmark",
		Tests:            []string{"TestC016_NoTaskImprovementClaimIsAsserted"},
		Result:           NotMeasured,
		Why:              "R1 established retrieval, not outcome. The R10 trial on 2026-09-30 stopped at a preregistered ceiling and the treatment arm never ran.",
	},

	// -------------------------------------------------------- the footprint
	{
		ID:          "RPL-C022",
		Text:        "The binary makes no network request except for commands the user explicitly types.",
		Asserted:    []string{"README.md:407", "plugins/replay/skills/replay-doctor/SKILL.md:9"},
		Scope:       "the shipped binary",
		Establishes: []string{"no telemetry, no beacon, no first-run call"},
		DoesNotEstablish: []string{
			"anything about the hosted installer, which is checked separately",
			"ASSUMPTION, not established: that a destination is reachable only through a URL literal in Go source. A host assembled at runtime from parts would not be seen by this scan",
		},
		Vocabulary: "",
		Oracle:     "static enumeration of outbound destinations in non-test code",
		Tests:      []string{"TestC022_OutboundDestinationsAreAnEnumeratedSet"},
		Result:     Bounded,
		Why:        "Checkable statically. A dynamic proof would need a sandboxed run and is not attempted here.",
	},
}
