package tui

import "testing"

// The width is a measurement, not a constant.
//
// It was BudgetCols = 80, and nothing read COLUMNS or asked the terminal. A
// tui-audit run found 88 lines across the nine screens that exceed a 60-column
// terminal, in both en_US and ja_JP, and the terminal wraps every one of them —
// which turns each aligned column into a ragged one.
//
// storyboard.go scene 25 is literally "Terminal narrower than 80" and specifies
// what should happen. The design anticipated this exact failure and nothing
// implemented it, because nothing connects the storyboard to the running code.
//
// The default has to stay 80 when there is no terminal to ask. The committed
// screen images are generated by a test with no TTY and no COLUMNS, and they
// are diffed in CI, so a default that moved would rewrite every one of them for
// a reason unrelated to any screen changing.

// CO1: with no terminal and no COLUMNS, the width is the design target.
//
// This is what keeps the committed SVGs stable. It is listed first because it
// is the one that breaks the most if it regresses.
func TestCO1_DefaultsTo80WithoutATerminal(t *testing.T) {
	t.Setenv("COLUMNS", "")
	if got := Cols(); got != 80 {
		t.Errorf("Cols() = %d with no terminal and no COLUMNS, want 80; the committed screen "+
			"images are generated in exactly this condition and would all be rewritten", got)
	}
}

// CO2: COLUMNS is honoured when it names a usable width.
func TestCO2_ReadsCOLUMNS(t *testing.T) {
	t.Setenv("COLUMNS", "60")
	if got := Cols(); got != 60 {
		t.Errorf("Cols() = %d, want 60: COLUMNS was set and ignored", got)
	}
}

// CO3: nonsense in COLUMNS falls back rather than propagating.
//
// A shell can export COLUMNS=0 or leave a stale value from another window.
// Rendering to zero cells produces nothing at all, and a negative pad panics
// strings.Repeat, so the fallback is the difference between a narrow screen and
// no screen.
func TestCO3_NonsenseFallsBack(t *testing.T) {
	for _, v := range []string{"0", "-40", "not-a-number", "3"} {
		t.Setenv("COLUMNS", v)
		got := Cols()
		if got < minCols {
			t.Errorf("COLUMNS=%q gave %d, below the %d floor: a width this small renders "+
				"nothing readable and can produce a negative pad", v, got, minCols)
		}
	}
}

// CO4: a very wide terminal does not stretch the layout indefinitely.
//
// The screens are designed at 80 and the tables are laid out for it. Letting a
// 400-column window stretch every row would not make the report more legible,
// it would make one line of every table 400 cells long.
func TestCO4_WideTerminalsAreCapped(t *testing.T) {
	t.Setenv("COLUMNS", "400")
	if got := Cols(); got > maxCols {
		t.Errorf("Cols() = %d on a 400-column terminal, above the %d cap", got, maxCols)
	}
}

// CO5: the constant is gone, so nothing can quietly go back to assuming 80.
//
// Cols() remains as a name because seven call sites use it, but it must
// resolve through the measurement. If someone reintroduces a literal, this
// notices.
func TestCO5_HeaderPadsToTheMeasuredWidth(t *testing.T) {
	t.Setenv("COLUMNS", "60")
	h := header("cost")
	if VisibleLen(h) > 60 {
		t.Errorf("header is %d cells in a 60-cell terminal:\n%q\n"+
			"The right-aligned version tag is padded to a fixed width rather than the real one",
			VisibleLen(h), h)
	}
	t.Setenv("COLUMNS", "")
	if got := VisibleLen(header("cost")); got != 80 {
		t.Errorf("header is %d cells with no terminal, want 80: the committed images assume it", got)
	}
}

// CO6: rendered rows are truncated to the measured width.
func TestCO6_RowsTruncateToTheMeasuredWidth(t *testing.T) {
	t.Setenv("COLUMNS", "50")
	long := "  this row is considerably longer than fifty columns and must be cut to fit"
	for _, line := range RenderRows([]Line{{Text: long}}, -1) {
		if VisibleLen(line) > 50 {
			t.Errorf("row is %d cells in a 50-cell terminal: %q", VisibleLen(line), line)
		}
	}
}
