package tui

import (
	"os"
	"strconv"
)

// How wide the screen actually is.
//
// This was `BudgetCols = 80`, a constant, and nothing read COLUMNS or asked the
// terminal. A tui-audit run found 88 lines across the nine screens that exceed
// a 60-column terminal, in both en_US and ja_JP, and the terminal wraps every
// one of them, which turns each aligned column into a ragged one.
//
// storyboard.go scene 25 is literally "Terminal narrower than 80" and describes
// what should happen instead. The design anticipated this exact failure. Nothing
// implemented it, because nothing connects the storyboard to the running code.
//
// The bounds are the interesting part of this file.
const (
	// defaultCols is what a process with no terminal renders at, and it is load
	// bearing. The committed screen images are generated by a test with no TTY
	// and no COLUMNS, and diffed in CI, so a default that moved would rewrite
	// all nine for a reason unrelated to any screen changing.
	defaultCols = 80

	// minCols is a floor rather than a preference. A shell can export COLUMNS=0,
	// or leave a stale value behind after a window closes; header() computes a
	// pad by subtraction, and a width smaller than the text it must hold yields
	// a negative pad, which panics strings.Repeat. Below this there is no
	// readable layout to render anyway.
	minCols = 40

	// maxCols caps the stretch. The tables are laid out for 80 and widening them
	// does not make a report more legible, it makes one row of every table 400
	// cells long on an unmaximised window.
	maxCols = 120
)

// Cols reports the width to lay out for.
//
// COLUMNS first, because that is what a caller sets deliberately — the audit
// harness, and anyone scripting a capture at a chosen width. Then the terminal
// itself, because a shell usually does not export COLUMNS and a fix that only
// fired when it did would mostly not fire. Then the default, which is what a
// pipe gets, and what keeps the committed images stable.
func Cols() int {
	n, err := strconv.Atoi(os.Getenv("COLUMNS"))
	if err != nil || n <= 0 {
		if c, ok := termCols(); ok {
			n = c
		} else {
			return defaultCols
		}
	}
	if n < minCols {
		return minCols
	}
	if n > maxCols {
		return maxCols
	}
	return n
}
