package tui

import (
	"os"
	"strconv"
)

// How wide the screen actually is.
//
// This was `BudgetCols = 80`, a constant, and nothing read COLUMNS or asked the
// terminal. A tui-audit run found 88 lines across the nine screens that exceed
// a 60-column terminal, in both en_US and ja_JP, and the terminal wraps every
// one of them, which turns each aligned column into a ragged one.
//
// storyboard.go scene 25 is literally "Terminal narrower than 80" and describes
// what should happen instead. The design anticipated this exact failure. Nothing
// implemented it, because nothing connects the storyboard to the running code.
//
// The bounds are the interesting part of this file.
const (
	// defaultCols is what a process with no terminal renders at, and it is load
	// bearing. The committed screen images are generated by a test with no TTY
	// and no COLUMNS, and diffed in CI, so a default that moved would rewrite
	// every one of them for a reason unrelated to any screen changing. This
	// said "all nine", which was never the number of committed images.
	defaultCols = 80

	// minCols is a floor rather than a preference. A shell can export COLUMNS=0,
	// or leave a stale value behind after a window closes; header() computes a
	// pad by subtraction, and a width smaller than the text it must hold yields
	// a negative pad, which panics strings.Repeat. Below this there is no
	// readable layout to render anyway.
	minCols = 40

	// maxCols caps the stretch. The tables are laid out for 80 and widening them
	// does not make a report more legible, it makes one row of every table 400
	// cells long on an unmaximised window.
	maxCols = 120

	// defaultLines is a VT100's height, for the same reason defaultCols is 80:
	// a process with no terminal still has to lay something out, and this is
	// the number every emulator has defaulted to since.
	defaultLines = 24

	// minLines is a floor, not a preference. A shell can export LINES=0, and a
	// screen laid out for zero rows shows nothing at all — the reader sees an
	// empty frame and concludes the tool is broken.
	minLines = 10

	// chromeLines is what the frame costs: a title, a blank, and the footer the
	// reader navigates by. Body subtracts it so no caller has to remember.
	chromeLines = 4
)

// Lines reports the height to lay out for.
//
// The same contract as Cols, in the same order, deliberately: LINES first
// because that is what a caller sets on purpose, then the terminal, then the
// default. Two functions answering the same kind of question by different rules
// is how a caller comes to trust one and not the other.
//
// Unlike Cols there is no cap. maxCols exists because a 400-cell table row is
// unreadable; height has no equivalent argument, since more rows is strictly
// more content visible and that is the whole reason somebody maximises a
// window.
func Lines() int {
	n, err := strconv.Atoi(os.Getenv("LINES"))
	if err != nil || n <= 0 {
		if _, r, ok := termSize(); ok && r > 0 {
			n = r
		} else {
			return defaultLines
		}
	}
	if n < minLines {
		return minLines
	}
	return n
}

// Body reports how many rows a screen has for its own content.
//
// A screen that lays out for the full height overruns by exactly the chrome it
// forgot, which is the arithmetic every caller would otherwise repeat and one
// of them would get wrong.
func Body() int {
	if n := Lines() - chromeLines; n > 0 {
		return n
	}
	return 1
}

// Cols reports the width to lay out for.
//
// COLUMNS first, because that is what a caller sets deliberately — the audit
// harness, and anyone scripting a capture at a chosen width. Then the terminal
// itself, because a shell usually does not export COLUMNS and a fix that only
// fired when it did would mostly not fire. Then the default, which is what a
// pipe gets, and what keeps the committed images stable.
func Cols() int {
	n, err := strconv.Atoi(os.Getenv("COLUMNS"))
	if err != nil || n <= 0 {
		if c, _, ok := termSize(); ok {
			n = c
		} else {
			return defaultCols
		}
	}
	if n < minCols {
		return minCols
	}
	if n > maxCols {
		return maxCols
	}
	return n
}
