// readme-install rewrites the install block in README.md from
// distribution/channels.json.
//
// The manifest is the one place a channel's status lives. The README used to
// carry its own copy in prose, and the two disagreed: the prose said packages
// were on the releases page while the manifest marked them building. A block
// that is generated cannot disagree with its source, and the test in this
// package fails CI when the block in README.md is not what the generator
// prints.
//
// Usage, from the module root:
//
//	go run ./scripts/readme-install
//
// Running it twice changes nothing. Only the text between the two marker
// comments is touched; the rest of the README is prose and stays prose.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	beginMarker = "<!-- install-matrix:begin -->"
	endMarker   = "<!-- install-matrix:end -->"
	generated   = "<!-- Generated by `go run ./scripts/readme-install` from distribution/channels.json. Edit the manifest, not this block. -->"
	opening     = "Every route below ends at the same signed release; verify any download with cosign as shown in the Releases footer."
)

type channel struct {
	Name    string `json:"name"`
	Command string `json:"command"`
	Verify  string `json:"verify"`
	Status  string `json:"status"`
	Gate    string `json:"gate"`
}

type manifest struct {
	Channels []channel `json:"channels"`
}

// render prints the block body for the manifest: the text that sits between
// the two markers, exclusive of the markers themselves.
//
// A row without a command is not a route a reader can take, whatever its
// status says, so it does not print. The manifest carries such rows for the
// weekly liveness check (pkg.go.dev, Renovate, listing sites), and they belong
// to that check rather than to an install section.
func render(raw []byte) (string, error) {
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return "", fmt.Errorf("parsing manifest: %w", err)
	}

	var b strings.Builder
	b.WriteString(generated + "\n")
	b.WriteString(opening + "\n")

	var coming, blocked []string
	for _, c := range m.Channels {
		if c.Command == "" {
			continue
		}
		switch c.Status {
		case "live":
			fmt.Fprintf(&b, "\n**%s**\n\n```sh\n%s\n```\n", c.Name, c.Command)
			if c.Verify != "" {
				fmt.Fprintf(&b, "\nCheck: `%s`\n", c.Verify)
			}
		case "building":
			coming = append(coming, c.Name)
		case "blocked":
			blocked = append(blocked, fmt.Sprintf("Not offered: %s (%s)", c.Name, c.Gate))
		}
	}
	if len(coming) > 0 {
		fmt.Fprintf(&b, "\nComing: %s.\n", strings.Join(coming, ", "))
	}
	for _, line := range blocked {
		b.WriteString("\n" + line + "\n")
	}
	return b.String(), nil
}

// extract returns the text between the markers in readme.
func extract(readme string) (string, error) {
	start := strings.Index(readme, beginMarker)
	if start == -1 {
		return "", errors.New("README.md has no " + beginMarker + " marker")
	}
	start += len(beginMarker)
	end := strings.Index(readme[start:], endMarker)
	if end == -1 {
		return "", errors.New("README.md has no " + endMarker + " marker after the begin marker")
	}
	return strings.TrimPrefix(readme[start:start+end], "\n"), nil
}

// splice replaces the text between the markers with body and returns the
// whole README. The markers stay on their own lines.
func splice(readme, body string) (string, error) {
	start := strings.Index(readme, beginMarker)
	if start == -1 {
		return "", errors.New("README.md has no " + beginMarker + " marker")
	}
	start += len(beginMarker)
	end := strings.Index(readme[start:], endMarker)
	if end == -1 {
		return "", errors.New("README.md has no " + endMarker + " marker after the begin marker")
	}
	return readme[:start] + "\n" + body + readme[start+end:], nil
}

// moduleRoot walks up from the working directory to the directory holding
// go.mod, so the generator runs from the module root and the tests run from
// the package directory against the same files.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above " + dir)
		}
		dir = parent
	}
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "readme-install:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := moduleRoot()
	if err != nil {
		return err
	}
	raw, err := os.ReadFile(filepath.Join(root, "distribution", "channels.json"))
	if err != nil {
		return err
	}
	body, err := render(raw)
	if err != nil {
		return err
	}
	readmePath := filepath.Join(root, "README.md")
	before, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	after, err := splice(string(before), body)
	if err != nil {
		return err
	}
	if after == string(before) {
		fmt.Println("readme-install: README.md already matches distribution/channels.json")
		return nil
	}
	if err := os.WriteFile(readmePath, []byte(after), 0o644); err != nil {
		return err
	}
	fmt.Println("readme-install: rewrote the install block in README.md")
	return nil
}
