// Code generated by scripts/fetch-rates.sh. DO NOT EDIT.

package money

// RatesDate is the ECB publication date of the table below.
//
// Printed beside every converted figure and checked for age before one is
// shown. A rate with no date is a rate nobody can judge.
const RatesDate = "2026-09-07"

// RatesSource names where the numbers came from, in the output as well as here.
const RatesSource = "European Central Bank reference rates"

// rates is US dollars to one unit of each currency, derived from the ECB's
// euro-based feed as rate(X) / rate(USD).
//
// These are REFERENCE rates. Nobody is billed at them. A card issuer converts
// at its own rate on its own settlement date and adds a foreign transaction
// fee, so a figure converted here is an indication of size and not a bill.
var rates = map[string]float64{
	"AUD": 1.386078,
	"BRL": 5.126140,
	"CAD": 1.382034,
	"CHF": 0.809241,
	"CNY": 6.710979,
	"CZK": 20.819997,
	"DKK": 6.431423,
	"EUR": 0.860437,
	"GBP": 0.739064,
	"HKD": 7.840217,
	"HUF": 312.510755,
	"IDR": 17646.954053,
	"ILS": 3.010755,
	"INR": 94.494063,
	"ISK": 121.149544,
	"JPY": 154.749613,
	"KRW": 1347.926347,
	"MXN": 16.912063,
	"MYR": 4.046033,
	"NOK": 9.270349,
	"NZD": 1.701945,
	"PHP": 62.640681,
	"PLN": 3.708742,
	"RON": 4.518930,
	"SEK": 9.604199,
	"SGD": 1.266219,
	"THB": 32.895371,
	"TRY": 48.433144,
	"ZAR": 15.991740,
}

// minorUnits is how many decimal places each currency actually has.
var minorUnits = map[string]int{
	"AUD": 2,
	"BRL": 2,
	"CAD": 2,
	"CHF": 2,
	"CNY": 2,
	"CZK": 2,
	"DKK": 2,
	"EUR": 2,
	"GBP": 2,
	"HKD": 2,
	"HUF": 2,
	"IDR": 2,
	"ILS": 2,
	"INR": 2,
	"ISK": 0,
	"JPY": 0,
	"KRW": 0,
	"MXN": 2,
	"MYR": 2,
	"NOK": 2,
	"NZD": 2,
	"PHP": 2,
	"PLN": 2,
	"RON": 2,
	"SEK": 2,
	"SGD": 2,
	"THB": 2,
	"TRY": 2,
	"ZAR": 2,
}
