package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/RedRobotKK/Replay/internal/analysis"
)

// The block an agent reads at boot.
//
// AGENTS.md is where several coding agents now look for project instructions,
// and CLAUDE.md is where one of them looks. Neither is a place to put a fact
// nobody can check, so this writes a block that says what it scanned, what it
// found, and what it did not look at.
//
// The thing worth telling an agent before it starts is not what the project
// costs. It is WHERE THE RECORDS ARE. A question answered from one directory,
// confidently and wrongly, is the failure this whole surface exists to prevent:
// on 2026-09-07 five files were read, all under funding/, and the authoritative
// record was in assets/applications/. Every source agreed and the agreement
// carried no information.
// maxBlockDirs bounds what goes into the prompt. Everything is still printed
// to stdout; only the injected block is capped.
const maxBlockDirs = 12

const (
	agentsBegin = "<!-- replay:sources:begin -->"
	agentsEnd   = "<!-- replay:sources:end -->"
)

func runAgents(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("agents", flag.ContinueOnError)
	fs.SetOutput(stderr)
	write := fs.String("write", "",
		"splice the block into this file between its markers, leaving everything else alone")
	if err := parseArgs(fs, args, stdout); err != nil {
		return err
	}
	root := "."
	if fs.NArg() > 0 {
		root = fs.Arg(0)
	}

	m, err := analysis.ScanSources(root)
	if err != nil {
		return fmt.Errorf("scan %s: %w", root, err)
	}
	block := agentsBlock(m)

	if *write == "" {
		_, err := io.WriteString(stdout, block)
		return err
	}

	old, rerr := os.ReadFile(*write)
	if rerr != nil && !os.IsNotExist(rerr) {
		return rerr
	}
	next := splice(string(old), block)
	if err := os.WriteFile(*write, []byte(next), 0o644); err != nil {
		return err
	}
	_, err = fmt.Fprintf(stdout, "\n  wrote the source block into %s (%d directories)\n\n", *write, len(m.Dirs))
	return err
}

// agentsBlock renders the markdown an agent reads.
//
// It leads with the instruction rather than the data, because an agent reading
// a list of directories does not know what it is for.
func agentsBlock(m analysis.SourceMap) string {
	var b strings.Builder
	b.WriteString(agentsBegin + "\n")
	b.WriteString("## Where this project's records are\n\n")
	b.WriteString("Generated by `replay agents`. Do not edit inside the markers, it is overwritten.\n\n")
	b.WriteString("**Before answering a question about what happened, what was sent, what was\n")
	b.WriteString("decided or what a figure was, check whether one of these holds the record.\n")
	b.WriteString("Sources drawn from a single directory agree by construction, and their\n")
	b.WriteString("agreement says nothing about whether the answer is complete.**\n\n")
	if len(m.Dirs) == 0 {
		b.WriteString("No record files were found by this scan.\n\n")
	} else {
		// Capped, and the cap is the point.
		//
		// This block is injected into the cached prefix of EVERY session, so
		// its size is not a formatting preference, it is a recurring cost paid
		// against the breaks it exists to prevent. On this corpus each 100
		// tokens of block costs roughly 853,000 token equivalents across the
		// whole period, so an unbounded listing of a large repository can cost
		// more than every preventable break combined. A directory name is what
		// an agent needs in order to go and look; the file names under it are
		// what it will find when it does.
		b.WriteString("```text\n")
		shown := m.Dirs
		if len(shown) > maxBlockDirs {
			shown = shown[:maxBlockDirs]
		}
		for _, d := range shown {
			fmt.Fprintf(&b, "%-40s %s\n", d.Dir+"/", d.Why)
		}
		b.WriteString("```\n\n")
		if len(m.Dirs) > len(shown) {
			fmt.Fprintf(&b, "%d more directories matched and are not listed here, to keep this "+
				"block small enough to be worth its place in every prompt. `replay agents` "+
				"prints all of them.\n\n", len(m.Dirs)-len(shown))
		}
	}
	b.WriteString(scopeNote(m))
	b.WriteString("\n" + agentsEnd + "\n")
	return b.String()
}

// scopeNote is the paragraph that keeps this honest.
//
// A list of sources read without its limits IS a claim of completeness, and
// this scan cannot make that claim. Render already writes this sentence for the
// terminal; it is reused verbatim so the two surfaces cannot drift into
// disagreeing about what was searched.
func scopeNote(m analysis.SourceMap) string {
	r := m.Render()
	i := strings.Index(r, "This is not a complete list")
	if i < 0 {
		return "This is not a complete list of where an answer might be.\n"
	}
	return r[i:]
}

// splice replaces the block between the markers and touches nothing else.
//
// A generated block living inside a hand-written file is only acceptable if the
// hand-written part is never at risk. Absent markers means append; malformed or
// reversed markers means append rather than guess, because a wrong guess here
// eats somebody's prose.
func splice(old, block string) string {
	i := strings.Index(old, agentsBegin)
	j := strings.Index(old, agentsEnd)
	if i < 0 || j < 0 || j < i {
		sep := "\n"
		if old != "" && !strings.HasSuffix(old, "\n") {
			sep = "\n\n"
		} else if old != "" {
			sep = "\n"
		}
		return old + sep + block
	}
	// Skip exactly one newline after the end marker if there is one, and
	// clamp. Indexing past the marker unconditionally assumed a trailing
	// newline, so a file saved without one panicked with a slice-bounds
	// error. This block is written into a file people are told to hand-edit,
	// which is the least acceptable place for a crash and the most likely.
	end := j + len(agentsEnd)
	if end < len(old) && old[end] == '\n' {
		end++
	}
	return old[:i] + block + old[end:]
}
