package main

import (
	"bytes"
	"strings"
	"testing"

	"github.com/RedRobotKK/Replay/internal/tui"
)

// The list of screens is written down once, or it drifts.
//
// It was written down three times: tui.Shortcuts(), the -screen flag's usage
// string, and the error a wrong -screen produces. The tenth screen, live, was
// added to the first and to neither of the others, so `replay tui --screen
// live` worked while the flag help and the error message both said it did not
// exist and both called the set "the nine". A working feature that every
// surface denies is indistinguishable from a broken one.

func screenLabels() []string {
	var out []string
	for _, s := range tui.Shortcuts() {
		out = append(out, s.Label)
	}
	return out
}

// SN1: the flag help names every screen.
func TestScreenFlagHelpNamesEveryScreen(t *testing.T) {
	var out bytes.Buffer
	// -h makes the FlagSet print its usage, which is where the list lives.
	_ = runTUI([]string{"-h"}, &out, &out)
	help := out.String()
	for _, l := range screenLabels() {
		if !strings.Contains(help, l) {
			t.Errorf("-screen help does not offer %q, which is a screen that exists:\n%s", l, help)
		}
	}
}

// SN2: and so does the error for a screen that does not.
//
// This is the message a reader gets at the moment they are already wrong about
// the screen names, so it is the worst place to be missing one.
func TestUnknownScreenErrorNamesEveryScreen(t *testing.T) {
	var out bytes.Buffer
	err := runTUI([]string{"-screen", "nosuchscreen"}, &out, &out)
	if err == nil {
		t.Fatal("an unknown screen was accepted")
	}
	msg := err.Error()
	for _, l := range screenLabels() {
		if !strings.Contains(msg, l) {
			t.Errorf("the error for an unknown screen does not list %q:\n%s", l, msg)
		}
	}
}

// SN3: and nothing calls the set by a count that has to be maintained by hand.
//
// "The nine" was accurate once. A number spelled into a sentence beside a list
// that grows is a claim with a maintenance cost and no owner.
func TestNothingCountsTheScreensInProse(t *testing.T) {
	var out bytes.Buffer
	err := runTUI([]string{"-screen", "nosuchscreen"}, &out, &out)
	if err == nil {
		t.Fatal("an unknown screen was accepted")
	}
	for _, n := range []string{"The nine", "the nine", "The ten", "the ten"} {
		if strings.Contains(err.Error(), n) {
			t.Errorf("the error counts the screens in prose (%q); the list is right "+
				"there and cannot go stale, the count can:\n%s", n, err.Error())
		}
	}
}

// SN4: `replay mcp --install` still installs, now that it goes through a
// FlagSet instead of a hand-written argument match in the dispatch switch.
//
// The reason it moved is that docs/CLI.md is generated by asking each
// subcommand what flags it has, and a flag matched by hand has none to give:
// the reference said "mcp: Takes no flags" while --install shipped and worked.
// This test is the one that would notice if the move broke it.
func TestMCPInstallStillPrintsTheConfiguration(t *testing.T) {
	for _, spelling := range []string{"--install", "-install"} {
		var out, errs bytes.Buffer
		if err := runMCPCommand([]string{spelling}, &out, &errs); err != nil {
			t.Fatalf("%s returned %v", spelling, err)
		}
		got := out.String()
		for _, want := range []string{"MCP configuration", "replay", "mcp"} {
			if !strings.Contains(got, want) {
				t.Errorf("%s does not print %q:\n%s", spelling, want, got)
			}
		}
		// And it must not have started serving: a server writes JSON-RPC, and
		// a snippet is not JSON-RPC.
		if strings.Contains(got, `"jsonrpc"`) {
			t.Errorf("%s served instead of printing the snippet:\n%s", spelling, got)
		}
	}
}
