#!/usr/bin/env bash
# Regenerate internal/money/rates.go from the ECB's daily reference rates.
#
# The rates are generated rather than typed, for the same reason the price
# table carries a version: a number in the source that nobody can reproduce is
# a number nobody can check. Run this, commit the diff, and the provenance is
# the diff.
#
# Source: the European Central Bank's euro foreign exchange reference rates,
# published each working day around 16:00 CET. They are reference rates, not
# transaction rates: the ECB says so itself, and it matters here. Nobody is
# billed at these. See internal/money/rates.go for what that means for the
# figures the tool prints.
#
# The feed is EUR-based, so USD->X is derived as rate(X) / rate(USD). That
# division is the reason USD itself is not in the generated table: it is the
# unit everything is expressed in, and 1.0 is not a measurement.
#
# Usage: scripts/fetch-rates.sh
set -euo pipefail

cd "$(dirname "$0")/.."

url="https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl -fsSL --proto '=https' --tlsv1.2 --max-time 30 -o "$tmp" "$url" \
  || { echo "could not fetch $url" >&2; exit 1; }

python3 - "$tmp" <<'PY'
import re, sys, datetime

raw = open(sys.argv[1], encoding="utf-8").read()

date = re.search(r"time='(\d{4}-\d{2}-\d{2})'", raw)
if not date:
    sys.exit("no date in the feed; refusing to write a table that cannot say when it is from")
date = date.group(1)

pairs = dict(re.findall(r"currency='([A-Z]{3})'\s+rate='([0-9.]+)'", raw))
if "USD" not in pairs:
    sys.exit("no USD in the feed; every rate here is derived through it")
usd = float(pairs["USD"])

# ISO 4217 minor units, for the currencies this feed carries. Everything the
# ECB publishes is 2 except the three below, and getting this wrong prints
# JPY with two decimal places that do not exist.
zero = {"JPY", "ISK", "KRW"}

# EUR is the feed's base and so is absent from its own list. Leaving it out
# would silently give every euro-area reader no conversion at all, which is the
# largest group this feature is for after the dollar.
rows = [("EUR", 1.0 / usd, 2)]
for code in sorted(pairs):
    if code == "USD":
        continue
    rows.append((code, float(pairs[code]) / usd, 0 if code in zero else 2))
rows.sort()

out = ['// Code generated by scripts/fetch-rates.sh. DO NOT EDIT.', '']
out.append('package money')
out.append('')
out.append('// RatesDate is the ECB publication date of the table below.')
out.append('//')
out.append('// Printed beside every converted figure and checked for age before one is')
out.append('// shown. A rate with no date is a rate nobody can judge.')
out.append(f'const RatesDate = "{date}"')
out.append('')
out.append('// RatesSource names where the numbers came from, in the output as well as here.')
out.append('const RatesSource = "European Central Bank reference rates"')
out.append('')
out.append('// rates is US dollars to one unit of each currency, derived from the ECB\'s')
out.append('// euro-based feed as rate(X) / rate(USD).')
out.append('//')
out.append('// These are REFERENCE rates. Nobody is billed at them. A card issuer converts')
out.append('// at its own rate on its own settlement date and adds a foreign transaction')
out.append('// fee, so a figure converted here is an indication of size and not a bill.')
out.append('var rates = map[string]float64{')
for code, rate, _ in rows:
    out.append(f'\t"{code}": {rate:.6f},')
out.append('}')
out.append('')
out.append('// minorUnits is how many decimal places each currency actually has.')
out.append('var minorUnits = map[string]int{')
for code, _, mu in rows:
    out.append(f'\t"{code}": {mu},')
out.append('}')
out.append('')

open("internal/money/rates.go", "w", encoding="utf-8").write("\n".join(out))
print(f"wrote internal/money/rates.go: {len(rows)} currencies, ECB date {date}")
PY

gofmt -w internal/money/rates.go
echo "remember to commit the diff; the provenance is the diff"
