// Package card renders the social card that `replay cost --share --png` writes.
//
// It draws text without a font library. `go.mod` is three lines, there is no
// `go.sum`, and "no dependencies" is a claim published on the README and on
// redrobot.jp — a promotional image is not worth weakening it for. So the
// rasterising happens once, on a developer's machine, in gen/atlas.py, and what
// ships is the result: three grayscale glyph atlases and a metrics sidecar,
// embedded and blended by the standard library alone.
//
// The cost of that trade is real and worth stating. There is no hinting, no
// kerning and no shaping, the glyph set is ASCII 32..126, and every size is a
// downsample of one 128px master. For a card that carries five numbers and a
// curl line, none of that shows. For body text it would.
package card

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"sync"
)

//go:embed atlas.json atlas-bold.png atlas-regular.png atlas-mono.png
var assets embed.FS

// faceMeta is the sidecar written by gen/atlas.py. Coordinates are in nominal
// units — pixels at the 128px master size — and every one is scaled by
// size/nominal at draw time.
type faceMeta struct {
	File     string    `json:"file"`
	CellW    int       `json:"cellW"`
	CellH    int       `json:"cellH"`
	OriginX  int       `json:"originX"`
	OriginY  int       `json:"originY"`
	Advances []float64 `json:"advances"`
	Source   string    `json:"source"`
}

type atlasMeta struct {
	Nominal int                 `json:"nominal"`
	First   int                 `json:"first"`
	Last    int                 `json:"last"`
	Faces   map[string]faceMeta `json:"faces"`
}

// face is one loaded atlas: the metrics plus the decoded master bitmap, with a
// cache of the per-size glyph cells derived from it.
type face struct {
	meta    faceMeta
	nominal int
	first   int
	last    int
	master  *image.Gray

	mu     sync.Mutex
	scaled map[int][]*image.Gray // size in px -> one cell per glyph, lazily filled
}

const (
	faceBold    = "bold"
	faceRegular = "regular"
	faceMono    = "mono"
)

var (
	loadOnce sync.Once
	faces    map[string]*face
	loadErr  error
)

// loadFaces decodes the embedded atlases once per process.
//
// A failure here is a broken build, not a runtime condition: the assets are
// compiled in, so if they do not decode they never decoded, on any machine. It
// is still returned rather than panicked, because a promotional image is not
// worth taking the process down for.
func loadFaces() (map[string]*face, error) {
	loadOnce.Do(func() {
		raw, err := assets.ReadFile("atlas.json")
		if err != nil {
			loadErr = fmt.Errorf("reading the embedded atlas metrics: %w", err)
			return
		}
		var meta atlasMeta
		if err := json.Unmarshal(raw, &meta); err != nil {
			loadErr = fmt.Errorf("parsing the embedded atlas metrics: %w", err)
			return
		}
		if meta.Nominal <= 0 || meta.Last <= meta.First {
			loadErr = fmt.Errorf("the embedded atlas metrics describe no glyphs: %+v", meta)
			return
		}
		out := make(map[string]*face, len(meta.Faces))
		for name, fm := range meta.Faces {
			n := meta.Last - meta.First + 1
			if len(fm.Advances) != n {
				loadErr = fmt.Errorf("face %s carries %d advances for %d glyphs; the "+
					"sidecar and the atlas disagree and every line would be laid out wrong",
					name, len(fm.Advances), n)
				return
			}
			b, err := assets.ReadFile(fm.File)
			if err != nil {
				loadErr = fmt.Errorf("reading the embedded atlas %s: %w", fm.File, err)
				return
			}
			img, err := png.Decode(bytes.NewReader(b))
			if err != nil {
				loadErr = fmt.Errorf("decoding the embedded atlas %s: %w", fm.File, err)
				return
			}
			g, ok := img.(*image.Gray)
			if !ok {
				// The generator writes mode "L". Anything else means the file
				// was regenerated by something that does not know that.
				g = image.NewGray(img.Bounds())
				for y := img.Bounds().Min.Y; y < img.Bounds().Max.Y; y++ {
					for x := img.Bounds().Min.X; x < img.Bounds().Max.X; x++ {
						r, _, _, _ := img.At(x, y).RGBA()
						g.SetGray(x, y, color.Gray{Y: uint8(r >> 8)})
					}
				}
			}
			if want := fm.CellW * n; g.Bounds().Dx() != want {
				loadErr = fmt.Errorf("atlas %s is %dpx wide but %d cells of %dpx is %dpx; "+
					"the sidecar does not describe this image",
					fm.File, g.Bounds().Dx(), n, fm.CellW, want)
				return
			}
			out[name] = &face{
				meta: fm, nominal: meta.Nominal, first: meta.First, last: meta.Last,
				master: g, scaled: map[int][]*image.Gray{},
			}
		}
		for _, want := range []string{faceBold, faceRegular, faceMono} {
			if out[want] == nil {
				loadErr = fmt.Errorf("the embedded atlas set has no %q face", want)
				return
			}
		}
		faces = out
	})
	return faces, loadErr
}

// index maps a byte to its glyph slot, or -1. Everything outside printable
// ASCII is dropped rather than substituted: a card that silently renders a
// tofu box in the middle of an install line is worse than one that never had
// the character, and no card copy contains anything outside this range.
func (f *face) index(c byte) int {
	if int(c) < f.first || int(c) > f.last {
		return -1
	}
	return int(c) - f.first
}

// cells returns the glyph bitmaps for this face at one pixel size, resampled
// from the master on first use and cached after.
func (f *face) cells(size int) []*image.Gray {
	f.mu.Lock()
	defer f.mu.Unlock()
	if got, ok := f.scaled[size]; ok {
		return got
	}
	scale := float64(size) / float64(f.nominal)
	w := int(float64(f.meta.CellW)*scale + 0.5)
	h := int(float64(f.meta.CellH)*scale + 0.5)
	if w < 1 {
		w = 1
	}
	if h < 1 {
		h = 1
	}
	n := f.last - f.first + 1
	out := make([]*image.Gray, n)
	for i := 0; i < n; i++ {
		cell := f.master.SubImage(image.Rect(
			i*f.meta.CellW, 0, (i+1)*f.meta.CellW, f.meta.CellH)).(*image.Gray)
		out[i] = resampleGray(cell, w, h)
	}
	f.scaled[size] = out
	return out
}

// advance is how far the pen moves after a glyph, in pixels at this size. It
// stays fractional: rounding per glyph accumulates to several characters of
// drift across a 58-character install line.
func (f *face) advance(c byte, size int) float64 {
	i := f.index(c)
	if i < 0 {
		return 0
	}
	return f.meta.Advances[i] * float64(size) / float64(f.nominal)
}
